### PR TITLE
Order keys in generated chart. Fixes #14

### LINKED ISSUE #14: No order in template

### PR DESCRIPTION
**Pull request by fireflycons**
Added a method to sort the map keys for the loop in Processor `walk` function

Keys are naturally string sorted except for the following:

* At root level, return `apiVersion`, `kind`, `metadata` first, then sort the rest
* At metadata level, return `name`, `namespace`, then sort the rest
* At container level, return `name`, `image`, `command`, `args`, then sort the rest

### CODE REVIEW

**Comment by yeahdongcn** [comment]
Thank you for the PR, @fireflycons.

`Sort map keys` looks unnecessary to me because we can dry-run the helm installation and use `yq` to do the final sort. This is clearer from my point of view as I don't need to worry about the intermediate states.

```bash
yq -i -P '... comments="" | sort_keys(..)' test/output/0200/mychart.yaml
```

**Comment by yeahdongcn** [comment]
Sorry, my bad. #14 was created before I found using `yq` might be easier.

**Comment by fireflycons** [comment]
I kinda disagree @yeahdongcn , since this creates a dependency on `yq` which isn't installed by default on most distros, plus you have a more complicated makefile. To work around some of the issues I've reported and before I started to fix them, I had to add to the makefile to get `yq` if needed, then post-process the output of kustohelmize. 

Furthermore, `yq` will throw its toys out if you point it at the generated helm templates as they're not valid YAML when you have conditional or range templates surrounding keys.

I actually thought it would be harder to fix inside the go code than it actually was. All I'm doing here is to guarantee the order of the map keys, when the documentation states that map keys are by default not ordered since map is a hash table behind the scenes.

Some of my other issues I reported are easier to fix if I can assume that the keys are ordered.

**Comment by fireflycons** [comment]
Also `yq` wouldn't do a custom sort order. I kinda like seeing it ordered as

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
   name: my-cm
data:
  ... 
```

A natural string sort would place `data` straight after `apiVersion`

**Comment by yeahdongcn** [comment]
> Some of my other issues I reported are easier to fix if I can assume that the keys are ordered - and indeed I have started fixing them.

Thanks for the further explanation. Let me merge this one first.

**Pull request merged**
